import path from 'node:path';
import fs from 'node:fs';
import { unanalyzedChanges, updateChange } from './lib/changelog';
import { loadSources } from './lib/sources';
import { fetchSource } from './lib/fetchSource';
import { readSnapshot } from './lib/snapshot';
import { complete, extractJson, llmAvailable, llmModel } from './lib/llm';
import { LENSES } from './lenses';
import { INTERNAL_LEADS_DIR } from './lib/paths';
import { ensureDir } from './lib/util';
import type { Source } from './lib/types';

const MAX_DOC_CHARS = 12000;

interface Lead {
  domain: string;
  concern: string;
  lead: string;
  difficulty?: 'low' | 'medium' | 'high';
}
interface AnalysisResult {
  publicSummary: string;
  leads: Lead[];
}

function buildSystemPrompt(): string {
  return [
    'You are the orchestrator for a community watchdog tracking the MD-PHX1 data center',
    '(City of Phoenix case 23-1632) in Ahwatukee. Your job is to review newly-changed source',
    'content and identify (a) a neutral, factual public summary of what changed, and (b) domain',
    'specific concerns and leads that could help residents lawfully slow or stop the project.',
    '',
    'Apply these expert lenses:',
    ...LENSES.map(
      (l) => `- ${l.title} [${l.domain}]: ${l.focus}\n    ${l.checklist.map((c) => '· ' + c).join('\n    ')}`,
    ),
    '',
    'STRICT GUARDRAILS:',
    '- The public summary MUST be factual, neutral, and non-inflammatory. No legal advice, no accusations.',
    '- Legal items are RESEARCH QUESTIONS / LEADS for the Alliance\'s attorney to vet, never advice or conclusions.',
    '- If the change is trivial (e.g., cosmetic, unrelated), say so and return an empty leads array.',
    '- Never fabricate permit numbers, dates, or filings. Only use what is present in the provided text.',
    '',
    'Respond with STRICT JSON only, matching:',
    '{ "publicSummary": string, "leads": [ { "domain": string, "concern": string, "lead": string, "difficulty": "low"|"medium"|"high" } ] }',
  ].join('\n');
}

function buildUserPrompt(source: Source, text: string): string {
  return [
    `SOURCE: ${source.title}`,
    `URL: ${source.url}`,
    `RELEVANT DOMAINS (hint): ${(source.domains ?? []).join(', ') || 'unknown'}`,
    '',
    'CHANGED / CURRENT CONTENT (truncated):',
    '"""',
    text.slice(0, MAX_DOC_CHARS),
    '"""',
  ].join('\n');
}

function renderLeadsMarkdown(source: Source, result: AnalysisResult, when: string): string {
  const lines: string[] = [];
  lines.push(`# Internal leads — ${source.title}`);
  lines.push('');
  lines.push(`- Source: ${source.url}`);
  lines.push(`- Detected: ${when}`);
  lines.push(`- Generated by: automated analysis (${llmModel()})`);
  lines.push('');
  lines.push('> AI-GENERATED, PENDING HUMAN REVIEW. Legal items are research leads for the');
  lines.push('> attorney to vet, not advice. Verify every date/number against the source.');
  lines.push('');
  lines.push('## Public summary (safe to publish)');
  lines.push('');
  lines.push(result.publicSummary || '(none)');
  lines.push('');
  lines.push('## Leads by domain');
  lines.push('');
  if (!result.leads || result.leads.length === 0) {
    lines.push('_No actionable leads identified for this change._');
  } else {
    for (const lead of result.leads) {
      lines.push(`### [${lead.domain}] ${lead.concern}`);
      lines.push('');
      lines.push(`- Lead: ${lead.lead}`);
      if (lead.difficulty) lines.push(`- Difficulty: ${lead.difficulty}`);
      lines.push('');
    }
  }
  return lines.join('\n') + '\n';
}

async function main() {
  const pending = unanalyzedChanges();
  console.log(`[analyze] unanalyzed changes: ${pending.length}`);
  if (pending.length === 0) return;

  if (!llmAvailable()) {
    console.log(
      '[analyze] ANTHROPIC_API_KEY not set — skipping analysis. Changes remain flagged as unanalyzed.',
    );
    return;
  }

  const sources = new Map(loadSources().map((s) => [s.id, s]));
  ensureDir(INTERNAL_LEADS_DIR);

  for (const { file, entry } of pending) {
    const source = entry.sourceId ? sources.get(entry.sourceId) : undefined;
    if (!source) {
      console.warn(`[analyze] ! ${entry.id}: source '${entry.sourceId}' not found; skipping`);
      continue;
    }

    // Prefer fresh content; fall back to the snapshot preview if the fetch fails.
    let text = '';
    const fresh = await fetchSource(source);
    if (fresh.ok) {
      text = fresh.text;
    } else {
      const snap = readSnapshot(source.id);
      text = snap?.preview ?? '';
      console.warn(`[analyze] ~ ${entry.id}: using snapshot preview (fetch failed: ${fresh.error})`);
    }

    if (!text) {
      console.warn(`[analyze] ! ${entry.id}: no content to analyze; skipping`);
      continue;
    }

    let result: AnalysisResult;
    try {
      const raw = await complete(buildSystemPrompt(), buildUserPrompt(source, text));
      const parsed = extractJson<AnalysisResult>(raw);
      result = parsed ?? {
        publicSummary: raw.slice(0, 500),
        leads: [],
      };
    } catch (err) {
      console.error(`[analyze] ! ${entry.id}: LLM error`, err);
      continue; // leave unanalyzed; retry next run
    }

    // Update the public changelog entry with the neutral summary.
    entry.summary = result.publicSummary || entry.summary;
    entry.analyzed = true;
    const leadDomains = Array.from(
      new Set([...(entry.domains ?? []), ...(result.leads ?? []).map((l) => l.domain)]),
    );
    entry.domains = leadDomains;
    updateChange(file, entry);

    // Write internal (unpublished) leads.
    const leadFile = path.join(INTERNAL_LEADS_DIR, `${entry.id}.md`);
    fs.writeFileSync(leadFile, renderLeadsMarkdown(source, result, entry.date), 'utf8');

    console.log(
      `[analyze] * ${entry.id}: analyzed (${result.leads?.length ?? 0} leads) -> ${path.basename(leadFile)}`,
    );
  }

  console.log('[analyze] done.');
}

main().catch((err) => {
  console.error('[analyze] fatal:', err);
  process.exit(1);
});
